
package GUI;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;


public class AdminPasswordPanel extends javax.swing.JFrame {

    AdminPanel adminPanel = new AdminPanel();
    WelcomePage wlcm;
    
    public AdminPasswordPanel(WelcomePage welcome) {
        setLocationRelativeTo(null); //center
        wlcm = welcome;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passwordTXT = new javax.swing.JPasswordField();
        readFromFileBTN = new javax.swing.JButton();
        passwordErrorTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Enter the password:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        passwordTXT.setOpaque(false);
        passwordTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTXTActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 200, -1));

        readFromFileBTN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        readFromFileBTN.setText("ENTER");
        readFromFileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readFromFileBTNActionPerformed(evt);
            }
        });
        readFromFileBTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                readFromFileBTNKeyPressed(evt);
            }
        });
        getContentPane().add(readFromFileBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        passwordErrorTXT.setEditable(false);
        passwordErrorTXT.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passwordErrorTXT.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        passwordErrorTXT.setEnabled(false);
        passwordErrorTXT.setOpaque(false);
        getContentPane().add(passwordErrorTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 330, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTXTActionPerformed

    private void readFromFileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readFromFileBTNActionPerformed
        String fileName = "password.txt";
        String suspiciousStr = passwordTXT.getText();
        passwordTXT.setText("");
        
        File file = new  File(fileName);
        Scanner sc;
        try {
            sc = new Scanner(file);
            String truePassword = sc.nextLine();
            
            if(truePassword.equals(suspiciousStr)){
                adminPanel.setVisible(true);
                this.dispose();
                wlcm.setVisible(false);
            }else{
              passwordErrorTXT.setText("WRONG PASSWORD TRY AGAIN !!!!!");
               
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminPasswordPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
       
    }//GEN-LAST:event_readFromFileBTNActionPerformed

    private void readFromFileBTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readFromFileBTNKeyPressed
        
    }//GEN-LAST:event_readFromFileBTNKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField passwordErrorTXT;
    private javax.swing.JPasswordField passwordTXT;
    private javax.swing.JButton readFromFileBTN;
    // End of variables declaration//GEN-END:variables
}
