package GUI;

import java.util.ArrayList;
import javaproject.DomesticFlight;
import javaproject.FlightSys;
import javaproject.Flight;
import javaproject.TicketSys;

public class CustomerPanel extends javax.swing.JFrame {

    WelcomePage WP;
    String flightType;

    public CustomerPanel(WelcomePage wlcm) {
        setLocationRelativeTo(null); //center
        initComponents();
        allFlightTXTarea.setText(FlightSys.display());
        WP = wlcm;

        String numOfFlight = Integer.toString(FlightSys.numberOfFlight());
        numberOfFlightTXT.setText(numOfFlight);
        flightType = (String) ticketTypeCMB.getSelectedItem();

        if (flightType.equals("International Flight")) {
            tcNOpanel.setVisible(false);
            InterFlightPanel.setVisible(true);
        } else {
            tcNOpanel.setVisible(true);
            InterFlightPanel.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        allFlightTXTarea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        numberOfFlightTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        disposeExitPanel = new javax.swing.JButton();
        ticketTypeCMB = new javax.swing.JComboBox<>();
        ticketPurchasePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        seatCMB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        flightNoTXT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nameSurnameTXT = new javax.swing.JTextField();
        purchaseTicket = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tcNOpanel = new javax.swing.JPanel();
        tcNoTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        InterFlightPanel = new javax.swing.JPanel();
        passportTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ticketPurchaseMessageTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allFlightTXTarea.setEditable(false);
        allFlightTXTarea.setColumns(20);
        allFlightTXTarea.setRows(5);
        allFlightTXTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(allFlightTXTarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, 480));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Number of flight(s): ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        numberOfFlightTXT.setEditable(false);
        numberOfFlightTXT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        numberOfFlightTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfFlightTXTActionPerformed(evt);
            }
        });
        getContentPane().add(numberOfFlightTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 40, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("BUY TICKET");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("ALL FLIGHTS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        disposeExitPanel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        disposeExitPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        disposeExitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disposeExitPanelActionPerformed(evt);
            }
        });
        getContentPane().add(disposeExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 70, 70));

        ticketTypeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domestic Flight", "International Flight", " " }));
        ticketTypeCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketTypeCMBActionPerformed(evt);
            }
        });
        getContentPane().add(ticketTypeCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 150, -1));

        ticketPurchasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Seat");
        ticketPurchasePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        seatCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "A2", "A3", "A4", "A5", "A6", "B1", "B2", "B3", "B4", "B5", "B6", "C1", "C2", "C3", "C4", "C5", "C6", "E1", "E2", "E3", "E4", "E5", "E6", "F1", "F2", "F3", "F4", "F5", "F6", "G1", "G2", "G3", "G4", "G5", "G6", " " }));
        ticketPurchasePanel.add(seatCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 60, -1));

        jLabel7.setText("Flight NO:");
        ticketPurchasePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        flightNoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightNoTXTActionPerformed(evt);
            }
        });
        ticketPurchasePanel.add(flightNoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 150, -1));

        jLabel8.setText("Name Surname:");
        ticketPurchasePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        ticketPurchasePanel.add(nameSurnameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 150, -1));

        purchaseTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purchase.png"))); // NOI18N
        purchaseTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseTicketActionPerformed(evt);
            }
        });
        ticketPurchasePanel.add(purchaseTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, 70));

        jLabel5.setText("BUY");
        ticketPurchasePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        tcNOpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tcNOpanel.add(tcNoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, -1));

        jLabel6.setText("TC NO:");
        tcNOpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 150, -1));

        jLabel12.setText("TC NO:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tcNOpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 70));

        ticketPurchasePanel.add(tcNOpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 370, 60));

        InterFlightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        InterFlightPanel.add(passportTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 150, -1));

        jLabel10.setText("Passport No");
        InterFlightPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 150, -1));

        jLabel13.setText("TC NO:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        InterFlightPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 70));

        ticketPurchasePanel.add(InterFlightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 390, 100));

        ticketPurchaseMessageTXT.setEditable(false);
        ticketPurchaseMessageTXT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ticketPurchaseMessageTXT.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        ticketPurchasePanel.add(ticketPurchaseMessageTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 310, -1));

        getContentPane().add(ticketPurchasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 410, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfFlightTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfFlightTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfFlightTXTActionPerformed

    private void disposeExitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disposeExitPanelActionPerformed
        WP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_disposeExitPanelActionPerformed

    private void ticketTypeCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketTypeCMBActionPerformed
        flightType = (String) ticketTypeCMB.getSelectedItem();

        if (flightType.equals("International Flight")) {
            tcNOpanel.setVisible(false);
            InterFlightPanel.setVisible(true);
        } else {
            tcNOpanel.setVisible(true);
            InterFlightPanel.setVisible(false);
        }
    }//GEN-LAST:event_ticketTypeCMBActionPerformed

    private void flightNoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightNoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightNoTXTActionPerformed

    private void purchaseTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseTicketActionPerformed
        String flightNo,nameSurname,seat,passportNo,tcNo;
        double cargoWeight;
     
       
        
        if (flightType.equals("Domestic Flight")) {
            
            
            try{
                flightNo = flightNoTXT.getText();
                nameSurname = nameSurnameTXT.getText();
                tcNo =tcNoTXT.getText();
                seat = (String) seatCMB.getSelectedItem();
                passportNo="-";
                
               if(flightNo.equalsIgnoreCase("") || nameSurname.equalsIgnoreCase("") || tcNo.equalsIgnoreCase(""))
                {
                    ticketPurchaseMessageTXT.setText("Please Fill all blanks!!!");
                    flightNoTXT.setText("");
                    nameSurnameTXT.setText("");
                    tcNoTXT.setText("");
                }else{
                    flightNoTXT.setText("");
                    nameSurnameTXT.setText("");
                    tcNoTXT.setText("");
                    
                    ArrayList<Flight> temp=FlightSys.getArr();
                    
                    for(Flight flt:temp){
                       
                        if(flt.checkId(flightNo)){
                           boolean exp=TicketSys.addTicket(flightType, flightNo,flt.getFlightDateTime(),flt.getFromToDest(),flt.getGate(), flt.getPrice(), tcNo, passportNo,0.0, seat,nameSurname);
                           if(exp){
                               ticketPurchaseMessageTXT.setText("Ticket purchased");
                               
                               System.out.println(TicketSys.displayTicket());
                              
                           }else{
                               ticketPurchaseMessageTXT.setText("Fligt No has not found!");
                               System.out.println(TicketSys.displayTicket());
                           }
                           
                            
                            
                            
                        }
                    
                    }
                    
                    
                }
            }catch(NumberFormatException ex){
                //System.out.println("Error");
            }
            
            
           
            
        } else {
            flightNo = flightNoTXT.getText();
            nameSurname = nameSurnameTXT.getText();
            tcNo = "0";
            seat = (String) seatCMB.getSelectedItem();
            passportNo = passportTXT.getText();
        }
        
        
        
        
        
    }//GEN-LAST:event_purchaseTicketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InterFlightPanel;
    private javax.swing.JTextArea allFlightTXTarea;
    private javax.swing.JButton disposeExitPanel;
    private javax.swing.JTextField flightNoTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField nameSurnameTXT;
    private javax.swing.JTextField numberOfFlightTXT;
    private javax.swing.JTextField passportTXT;
    private javax.swing.JButton purchaseTicket;
    private javax.swing.JComboBox<String> seatCMB;
    private javax.swing.JPanel tcNOpanel;
    private javax.swing.JTextField tcNoTXT;
    private javax.swing.JTextField ticketPurchaseMessageTXT;
    private javax.swing.JPanel ticketPurchasePanel;
    private javax.swing.JComboBox<String> ticketTypeCMB;
    // End of variables declaration//GEN-END:variables
}
