/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javaproject.TicketSys;

/**
 *
 * @author ugure
 */
public class My_Ticket extends javax.swing.JFrame {
        TicketSys TS = new TicketSys();
    
    /**
     * Creates new form My_Ticket
     */
    public My_Ticket() {
        initComponents();
        TicketSys.calculateAllTicketPrice(); 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allTicketTxtArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        totalPriceTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deleteFlightNoTXT = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        delete_btn = new javax.swing.JButton();
        myTicketActionInfoTXT = new javax.swing.JTextField();
        showTicketBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("DELETE TICKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        allTicketTxtArea.setEditable(false);
        allTicketTxtArea.setColumns(20);
        allTicketTxtArea.setRows(5);
        jScrollPane1.setViewportView(allTicketTxtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 330));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("TL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        totalPriceTXT.setEditable(false);
        totalPriceTXT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        totalPriceTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceTXTActionPerformed(evt);
            }
        });
        getContentPane().add(totalPriceTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 100, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("TOTAL PAYMENT:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("MY TICKET(S)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel5.setText("FLIGHT NO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 60, -1));

        deleteFlightNoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFlightNoTXTActionPerformed(evt);
            }
        });
        getContentPane().add(deleteFlightNoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_ticket.png"))); // NOI18N
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 80, 80));

        myTicketActionInfoTXT.setEditable(false);
        myTicketActionInfoTXT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(myTicketActionInfoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 240, -1));

        showTicketBtn.setText("Refresh Ticket List");
        showTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTicketBtnActionPerformed(evt);
            }
        });
        getContentPane().add(showTicketBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteFlightNoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFlightNoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteFlightNoTXTActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
       
        String flightNothatDeleted = deleteFlightNoTXT.getText();
       if(!flightNothatDeleted.isEmpty()){
            boolean res=TicketSys.removeTicket(flightNothatDeleted);
            if(res){
                    myTicketActionInfoTXT.setText("Flight deleted");
                    allTicketTxtArea.setText(TicketSys.displayTicket()); //refresh the ticket txt area
                    totalPriceTXT.setText(TS.totalTicketPrice()+"");
                }
            else{
                myTicketActionInfoTXT.setText("Flight no has not found!");
            }
       }else{
            myTicketActionInfoTXT.setText("Add a valid flight no!");
       }
      
    }//GEN-LAST:event_delete_btnActionPerformed

    private void showTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTicketBtnActionPerformed
        TicketSys.calculateAllTicketPrice(); 
        allTicketTxtArea.setText(TicketSys.displayTicket());
        
       
         totalPriceTXT.setText(TS.totalTicketPrice()+"");
        
       
         
    }//GEN-LAST:event_showTicketBtnActionPerformed

    private void totalPriceTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPriceTXTActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea allTicketTxtArea;
    private javax.swing.JTextField deleteFlightNoTXT;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField myTicketActionInfoTXT;
    private javax.swing.JButton showTicketBtn;
    private javax.swing.JTextField totalPriceTXT;
    // End of variables declaration//GEN-END:variables
}
